<?php
namespace App\Modules\SuperAdmin\Database\Seeders;

use Illuminate\Support\Arr;
use Illuminate\Database\Seeder;
use App\Modules\SalesRep\Models\SalesRep;
use App\Modules\SuperAdmin\Models\Product;

class ProductSaleRecordsTableSeeder extends Seeder
{

  /**
   * Auto generated seed file
   *
   * @return void
   */
  public function run()
  {


    \DB::table('product_sale_records')->delete();

    \DB::table('product_sale_records')->insert(array(
      0 =>
      array(
        'product_id' => 22,
        'product_type' => Product::class,
        'selling_price' => 70000.0,
        'walk_in_rep_bonus' => $share = (($bonus = Arr::random([500, 1000])) * Arr::random([1, 0.3])),
        'online_rep_bonus' => $bonus - $share,
        'sales_channel_id' => 2,
        'online_rep_id' => random_int(2, 16),
        'sales_rep_id' => random_int(2, 10),
        'sales_rep_type' => SalesRep::class,
        'sale_confirmed_by' => 1,
        'sale_confirmer_type' => 'App\\Modules\\Admin\\Models\\Admin',
        'is_swap_transaction' => 0,
        'created_at' => '2020-06-17 00:00:00',
        'updated_at' => '2020-06-14 00:00:00',
        'deleted_at' => NULL,
      ),
      1 =>
      array(
        'product_id' => 15,
        'product_type' => Product::class,
        'selling_price' => 20000.0,
        'walk_in_rep_bonus' => $share = (($bonus = Arr::random([500, 1000])) * Arr::random([1, 0.3])),
        'online_rep_bonus' => $bonus - $share,
        'sales_channel_id' => 2,
        'online_rep_id' => random_int(2, 16),
        'sales_rep_id' => random_int(2, 10),
        'sales_rep_type' => SalesRep::class,
        'sale_confirmed_by' => NULL,
        'sale_confirmer_type' => NULL,
        'is_swap_transaction' => 0,
        'created_at' => '2020-06-12 00:00:00',
        'updated_at' => '2020-06-10 00:00:00',
        'deleted_at' => NULL,
      ),
      2 =>
      array(
        'product_id' => 43,
        'product_type' => Product::class,
        'selling_price' => 190000.0,
        'walk_in_rep_bonus' => $share = (($bonus = Arr::random([500, 1000])) * Arr::random([1, 0.3])),
        'online_rep_bonus' => $bonus - $share,
        'sales_channel_id' => 4,
        'online_rep_id' => random_int(2, 16),
        'sales_rep_id' => random_int(2, 10),
        'sales_rep_type' => SalesRep::class,
        'sale_confirmed_by' => NULL,
        'sale_confirmer_type' => NULL,
        'is_swap_transaction' => 0,
        'created_at' => '2020-06-07 00:00:00',
        'updated_at' => '2020-06-05 00:00:00',
        'deleted_at' => NULL,
      ),
      3 =>
      array(
        'product_id' => 3,
        'product_type' => Product::class,
        'selling_price' => 10000.0,
        'walk_in_rep_bonus' => $share = (($bonus = Arr::random([500, 1000])) * Arr::random([1, 0.3])),
        'online_rep_bonus' => $bonus - $share,
        'sales_channel_id' => 6,
        'online_rep_id' => random_int(2, 16),
        'sales_rep_id' => random_int(2, 10),
        'sales_rep_type' => SalesRep::class,
        'sale_confirmed_by' => NULL,
        'sale_confirmer_type' => NULL,
        'is_swap_transaction' => 0,
        'created_at' => '2020-06-03 00:00:00',
        'updated_at' => '2020-05-31 00:00:00',
        'deleted_at' => NULL,
      ),
      4 =>
      array(
        'product_id' => 14,
        'product_type' => Product::class,
        'selling_price' => 30000.0,
        'walk_in_rep_bonus' => $share = (($bonus = Arr::random([500, 1000])) * Arr::random([1, 0.3])),
        'online_rep_bonus' => $bonus - $share,
        'sales_channel_id' => 6,
        'online_rep_id' => random_int(2, 16),
        'sales_rep_id' => random_int(2, 10),
        'sales_rep_type' => SalesRep::class,
        'sale_confirmed_by' => NULL,
        'sale_confirmer_type' => NULL,
        'is_swap_transaction' => 0,
        'created_at' => '2020-05-29 00:00:00',
        'updated_at' => '2020-05-27 00:00:00',
        'deleted_at' => NULL,
      ),
      5 =>
      array(
        'product_id' => 29,
        'product_type' => Product::class,
        'selling_price' => 120000.0,
        'walk_in_rep_bonus' => $share = (($bonus = Arr::random([500, 1000])) * Arr::random([1, 0.3])),
        'online_rep_bonus' => $bonus - $share,
        'sales_channel_id' => 3,
        'online_rep_id' => random_int(2, 16),
        'sales_rep_id' => random_int(2, 10),
        'sales_rep_type' => SalesRep::class,
        'sale_confirmed_by' => NULL,
        'sale_confirmer_type' => NULL,
        'is_swap_transaction' => 0,
        'created_at' => '2020-05-24 00:00:00',
        'updated_at' => '2020-05-22 00:00:00',
        'deleted_at' => NULL,
      ),
      6 =>
      array(
        'product_id' => 16,
        'product_type' => Product::class,
        'selling_price' => 90000.0,
        'walk_in_rep_bonus' => $share = (($bonus = Arr::random([500, 1000])) * Arr::random([1, 0.3])),
        'online_rep_bonus' => $bonus - $share,
        'sales_channel_id' => 3,
        'online_rep_id' => random_int(2, 16),
        'sales_rep_id' => random_int(2, 10),
        'sales_rep_type' => SalesRep::class,
        'sale_confirmed_by' => NULL,
        'sale_confirmer_type' => NULL,
        'is_swap_transaction' => 0,
        'created_at' => '2020-05-20 00:00:00',
        'updated_at' => '2020-05-17 00:00:00',
        'deleted_at' => NULL,
      ),
      7 =>
      array(
        'product_id' => 46,
        'product_type' => Product::class,
        'selling_price' => 280000.0,
        'walk_in_rep_bonus' => $share = (($bonus = Arr::random([500, 1000])) * Arr::random([1, 0.3])),
        'online_rep_bonus' => $bonus - $share,
        'sales_channel_id' => 1,
        'online_rep_id' => random_int(2, 16),
        'sales_rep_id' => random_int(2, 10),
        'sales_rep_type' => SalesRep::class,
        'sale_confirmed_by' => NULL,
        'sale_confirmer_type' => NULL,
        'is_swap_transaction' => 0,
        'created_at' => '2020-05-15 00:00:00',
        'updated_at' => '2020-05-13 00:00:00',
        'deleted_at' => NULL,
      ),
      8 =>
      array(
        'product_id' => 18,
        'product_type' => Product::class,
        'selling_price' => 90000.0,
        'walk_in_rep_bonus' => $share = (($bonus = Arr::random([500, 1000])) * Arr::random([1, 0.3])),
        'online_rep_bonus' => $bonus - $share,
        'sales_channel_id' => 7,
        'online_rep_id' => random_int(2, 16),
        'sales_rep_id' => random_int(2, 10),
        'sales_rep_type' => SalesRep::class,
        'sale_confirmed_by' => NULL,
        'sale_confirmer_type' => NULL,
        'is_swap_transaction' => 0,
        'created_at' => '2020-05-10 00:00:00',
        'updated_at' => '2020-05-08 00:00:00',
        'deleted_at' => NULL,
      ),
      9 =>
      array(
        'product_id' => 47,
        'product_type' => Product::class,
        'selling_price' => 140000.0,
        'walk_in_rep_bonus' => $share = (($bonus = Arr::random([500, 1000])) * Arr::random([1, 0.3])),
        'online_rep_bonus' => $bonus - $share,
        'sales_channel_id' => 2,
        'online_rep_id' => random_int(2, 16),
        'sales_rep_id' => random_int(2, 10),
        'sales_rep_type' => SalesRep::class,
        'sale_confirmed_by' => NULL,
        'sale_confirmer_type' => NULL,
        'is_swap_transaction' => 0,
        'created_at' => '2020-05-06 00:00:00',
        'updated_at' => '2020-05-03 00:00:00',
        'deleted_at' => NULL,
      ),
      10 =>
      array(
        'product_id' => 31,
        'product_type' => Product::class,
        'selling_price' => 20000.0,
        'walk_in_rep_bonus' => $share = (($bonus = Arr::random([500, 1000])) * Arr::random([1, 0.3])),
        'online_rep_bonus' => $bonus - $share,
        'sales_channel_id' => 2,
        'online_rep_id' => random_int(2, 16),
        'sales_rep_id' => random_int(2, 10),
        'sales_rep_type' => SalesRep::class,
        'sale_confirmed_by' => NULL,
        'sale_confirmer_type' => NULL,
        'is_swap_transaction' => 0,
        'created_at' => '2020-05-01 00:00:00',
        'updated_at' => '2020-04-29 00:00:00',
        'deleted_at' => NULL,
      ),
      11 =>
      array(
        'product_id' => 24,
        'product_type' => Product::class,
        'selling_price' => 60000.0,
        'walk_in_rep_bonus' => $share = (($bonus = Arr::random([500, 1000])) * Arr::random([1, 0.3])),
        'online_rep_bonus' => $bonus - $share,
        'sales_channel_id' => 4,
        'online_rep_id' => random_int(2, 16),
        'sales_rep_id' => random_int(2, 10),
        'sales_rep_type' => SalesRep::class,
        'sale_confirmed_by' => NULL,
        'sale_confirmer_type' => NULL,
        'is_swap_transaction' => 0,
        'created_at' => '2020-04-26 00:00:00',
        'updated_at' => '2020-04-24 00:00:00',
        'deleted_at' => NULL,
      ),
      12 =>
      array(
        'product_id' => 30,
        'product_type' => Product::class,
        'selling_price' => 120000.0,
        'walk_in_rep_bonus' => $share = (($bonus = Arr::random([500, 1000])) * Arr::random([1, 0.3])),
        'online_rep_bonus' => $bonus - $share,
        'sales_channel_id' => 6,
        'online_rep_id' => random_int(2, 16),
        'sales_rep_id' => random_int(2, 10),
        'sales_rep_type' => SalesRep::class,
        'sale_confirmed_by' => NULL,
        'sale_confirmer_type' => NULL,
        'is_swap_transaction' => 0,
        'created_at' => '2020-04-22 00:00:00',
        'updated_at' => '2020-04-19 00:00:00',
        'deleted_at' => NULL,
      ),
      13 =>
      array(
        'product_id' => 6,
        'product_type' => Product::class,
        'selling_price' => 80000.0,
        'walk_in_rep_bonus' => $share = (($bonus = Arr::random([500, 1000])) * Arr::random([1, 0.3])),
        'online_rep_bonus' => $bonus - $share,
        'sales_channel_id' => 4,
        'online_rep_id' => random_int(2, 16),
        'sales_rep_id' => random_int(2, 10),
        'sales_rep_type' => SalesRep::class,
        'sale_confirmed_by' => NULL,
        'sale_confirmer_type' => NULL,
        'is_swap_transaction' => 0,
        'created_at' => '2020-04-17 00:00:00',
        'updated_at' => '2020-04-15 00:00:00',
        'deleted_at' => NULL,
      ),
      14 =>
      array(
        'product_id' => 28,
        'product_type' => Product::class,
        'selling_price' => 220000.0,
        'walk_in_rep_bonus' => $share = (($bonus = Arr::random([500, 1000])) * Arr::random([1, 0.3])),
        'online_rep_bonus' => $bonus - $share,
        'sales_channel_id' => 4,
        'online_rep_id' => random_int(2, 16),
        'sales_rep_id' => random_int(2, 10),
        'sales_rep_type' => SalesRep::class,
        'sale_confirmed_by' => NULL,
        'sale_confirmer_type' => NULL,
        'is_swap_transaction' => 0,
        'created_at' => '2020-04-13 00:00:00',
        'updated_at' => '2020-04-10 00:00:00',
        'deleted_at' => NULL,
      ),
      15 =>
      array(
        'product_id' => 5,
        'product_type' => Product::class,
        'selling_price' => 220000.0,
        'walk_in_rep_bonus' => $share = (($bonus = Arr::random([500, 1000])) * Arr::random([1, 0.3])),
        'online_rep_bonus' => $bonus - $share,
        'sales_channel_id' => 5,
        'online_rep_id' => random_int(2, 16),
        'sales_rep_id' => random_int(2, 10),
        'sales_rep_type' => SalesRep::class,
        'sale_confirmed_by' => NULL,
        'sale_confirmer_type' => NULL,
        'is_swap_transaction' => 0,
        'created_at' => '2020-04-08 00:00:00',
        'updated_at' => '2020-04-06 00:00:00',
        'deleted_at' => NULL,
      ),
      16 =>
      array(
        'product_id' => 13,
        'product_type' => Product::class,
        'selling_price' => 100000.0,
        'walk_in_rep_bonus' => $share = (($bonus = Arr::random([500, 1000])) * Arr::random([1, 0.3])),
        'online_rep_bonus' => $bonus - $share,
        'sales_channel_id' => 7,
        'online_rep_id' => random_int(2, 16),
        'sales_rep_id' => random_int(2, 10),
        'sales_rep_type' => SalesRep::class,
        'sale_confirmed_by' => NULL,
        'sale_confirmer_type' => NULL,
        'is_swap_transaction' => 0,
        'created_at' => '2020-04-03 00:00:00',
        'updated_at' => '2020-04-01 00:00:00',
        'deleted_at' => NULL,
      ),
      17 =>
      array(
        'product_id' => 9,
        'product_type' => Product::class,
        'selling_price' => 200000.0,
        'walk_in_rep_bonus' => $share = (($bonus = Arr::random([500, 1000])) * Arr::random([1, 0.3])),
        'online_rep_bonus' => $bonus - $share,
        'sales_channel_id' => 1,
        'online_rep_id' => random_int(2, 16),
        'sales_rep_id' => random_int(2, 10),
        'sales_rep_type' => SalesRep::class,
        'sale_confirmed_by' => NULL,
        'sale_confirmer_type' => NULL,
        'is_swap_transaction' => 0,
        'created_at' => '2020-03-30 00:00:00',
        'updated_at' => '2020-03-27 00:00:00',
        'deleted_at' => NULL,
      ),
      18 =>
      array(
        'product_id' => 17,
        'product_type' => Product::class,
        'selling_price' => 40000.0,
        'walk_in_rep_bonus' => $share = (($bonus = Arr::random([500, 1000])) * Arr::random([1, 0.3])),
        'online_rep_bonus' => $bonus - $share,
        'sales_channel_id' => 5,
        'online_rep_id' => random_int(2, 16),
        'sales_rep_id' => random_int(2, 10),
        'sales_rep_type' => SalesRep::class,
        'sale_confirmed_by' => NULL,
        'sale_confirmer_type' => NULL,
        'is_swap_transaction' => 0,
        'created_at' => '2020-03-25 00:00:00',
        'updated_at' => '2020-03-23 00:00:00',
        'deleted_at' => NULL,
      ),
      19 =>
      array(
        'product_id' => 21,
        'product_type' => Product::class,
        'selling_price' => 140000.0,
        'walk_in_rep_bonus' => $share = (($bonus = Arr::random([500, 1000])) * Arr::random([1, 0.3])),
        'online_rep_bonus' => $bonus - $share,
        'sales_channel_id' => 8,
        'online_rep_id' => random_int(2, 16),
        'sales_rep_id' => random_int(2, 10),
        'sales_rep_type' => SalesRep::class,
        'sale_confirmed_by' => NULL,
        'sale_confirmer_type' => NULL,
        'is_swap_transaction' => 0,
        'created_at' => '2020-03-20 00:00:00',
        'updated_at' => '2020-03-18 00:00:00',
        'deleted_at' => NULL,
      ),
      20 =>
      array(
        'product_id' => 7,
        'product_type' => Product::class,
        'selling_price' => 260000.0,
        'walk_in_rep_bonus' => $share = (($bonus = Arr::random([500, 1000])) * Arr::random([1, 0.3])),
        'online_rep_bonus' => $bonus - $share,
        'sales_channel_id' => 8,
        'online_rep_id' => random_int(2, 16),
        'sales_rep_id' => random_int(2, 10),
        'sales_rep_type' => SalesRep::class,
        'sale_confirmed_by' => NULL,
        'sale_confirmer_type' => NULL,
        'is_swap_transaction' => 0,
        'created_at' => '2020-03-16 00:00:00',
        'updated_at' => '2020-03-13 00:00:00',
        'deleted_at' => NULL,
      ),
      21 =>
      array(
        'product_id' => 20,
        'product_type' => Product::class,
        'selling_price' => 50000.0,
        'walk_in_rep_bonus' => $share = (($bonus = Arr::random([500, 1000])) * Arr::random([1, 0.3])),
        'online_rep_bonus' => $bonus - $share,
        'sales_channel_id' => 7,
        'online_rep_id' => random_int(2, 16),
        'sales_rep_id' => random_int(2, 10),
        'sales_rep_type' => SalesRep::class,
        'sale_confirmed_by' => NULL,
        'sale_confirmer_type' => NULL,
        'is_swap_transaction' => 0,
        'created_at' => '2020-03-11 00:00:00',
        'updated_at' => '2020-03-09 00:00:00',
        'deleted_at' => NULL,
      ),
      22 =>
      array(
        'product_id' => 11,
        'product_type' => Product::class,
        'selling_price' => 160000.0,
        'walk_in_rep_bonus' => $share = (($bonus = Arr::random([500, 1000])) * Arr::random([1, 0.3])),
        'online_rep_bonus' => $bonus - $share,
        'sales_channel_id' => 8,
        'online_rep_id' => random_int(2, 16),
        'sales_rep_id' => random_int(2, 10),
        'sales_rep_type' => SalesRep::class,
        'sale_confirmed_by' => NULL,
        'sale_confirmer_type' => NULL,
        'is_swap_transaction' => 0,
        'created_at' => '2020-03-06 00:00:00',
        'updated_at' => '2020-03-04 00:00:00',
        'deleted_at' => NULL,
      ),
      23 =>
      array(
        'product_id' => 36,
        'product_type' => Product::class,
        'selling_price' => 180000.0,
        'walk_in_rep_bonus' => $share = (($bonus = Arr::random([500, 1000])) * Arr::random([1, 0.3])),
        'online_rep_bonus' => $bonus - $share,
        'sales_channel_id' => 5,
        'online_rep_id' => random_int(2, 16),
        'sales_rep_id' => random_int(2, 10),
        'sales_rep_type' => SalesRep::class,
        'sale_confirmed_by' => NULL,
        'sale_confirmer_type' => NULL,
        'is_swap_transaction' => 0,
        'created_at' => '2020-03-02 00:00:00',
        'updated_at' => '2020-02-28 00:00:00',
        'deleted_at' => NULL,
      ),
      24 =>
      array(
        'product_id' => 32,
        'product_type' => Product::class,
        'selling_price' => 100000.0,
        'walk_in_rep_bonus' => $share = (($bonus = Arr::random([500, 1000])) * Arr::random([1, 0.3])),
        'online_rep_bonus' => $bonus - $share,
        'sales_channel_id' => 7,
        'online_rep_id' => random_int(2, 16),
        'sales_rep_id' => random_int(2, 10),
        'sales_rep_type' => SalesRep::class,
        'sale_confirmed_by' => NULL,
        'sale_confirmer_type' => NULL,
        'is_swap_transaction' => 0,
        'created_at' => '2020-02-26 00:00:00',
        'updated_at' => '2020-02-24 00:00:00',
        'deleted_at' => NULL,
      ),
      25 =>
      array(
        'product_id' => 4,
        'product_type' => Product::class,
        'selling_price' => 300000.0,
        'walk_in_rep_bonus' => $share = (($bonus = Arr::random([500, 1000])) * Arr::random([1, 0.3])),
        'online_rep_bonus' => $bonus - $share,
        'sales_channel_id' => 6,
        'online_rep_id' => random_int(2, 16),
        'sales_rep_id' => random_int(2, 10),
        'sales_rep_type' => SalesRep::class,
        'sale_confirmed_by' => NULL,
        'sale_confirmer_type' => NULL,
        'is_swap_transaction' => 0,
        'created_at' => '2020-02-21 00:00:00',
        'updated_at' => '2020-02-19 00:00:00',
        'deleted_at' => NULL,
      ),
      26 =>
      array(
        'product_id' => 23,
        'product_type' => Product::class,
        'selling_price' => 190000.0,
        'walk_in_rep_bonus' => $share = (($bonus = Arr::random([500, 1000])) * Arr::random([1, 0.3])),
        'online_rep_bonus' => $bonus - $share,
        'sales_channel_id' => 2,
        'online_rep_id' => random_int(2, 16),
        'sales_rep_id' => random_int(2, 10),
        'sales_rep_type' => SalesRep::class,
        'sale_confirmed_by' => NULL,
        'sale_confirmer_type' => NULL,
        'is_swap_transaction' => 0,
        'created_at' => '2020-02-17 00:00:00',
        'updated_at' => '2020-02-14 00:00:00',
        'deleted_at' => NULL,
      ),
      27 =>
      array(
        'product_id' => 19,
        'product_type' => Product::class,
        'selling_price' => 170000.0,
        'walk_in_rep_bonus' => $share = (($bonus = Arr::random([500, 1000])) * Arr::random([1, 0.3])),
        'online_rep_bonus' => $bonus - $share,
        'sales_channel_id' => 3,
        'online_rep_id' => random_int(2, 16),
        'sales_rep_id' => random_int(2, 10),
        'sales_rep_type' => SalesRep::class,
        'sale_confirmed_by' => NULL,
        'sale_confirmer_type' => NULL,
        'is_swap_transaction' => 0,
        'created_at' => '2020-02-12 00:00:00',
        'updated_at' => '2020-02-10 00:00:00',
        'deleted_at' => NULL,
      ),
      28 =>
      array(
        'product_id' => 48,
        'product_type' => Product::class,
        'selling_price' => 260000.0,
        'walk_in_rep_bonus' => $share = (($bonus = Arr::random([500, 1000])) * Arr::random([1, 0.3])),
        'online_rep_bonus' => $bonus - $share,
        'sales_channel_id' => 7,
        'online_rep_id' => random_int(2, 16),
        'sales_rep_id' => random_int(2, 10),
        'sales_rep_type' => SalesRep::class,
        'sale_confirmed_by' => NULL,
        'sale_confirmer_type' => NULL,
        'is_swap_transaction' => 0,
        'created_at' => '2020-02-08 00:00:00',
        'updated_at' => '2020-02-05 00:00:00',
        'deleted_at' => NULL,
      ),
      29 =>
      array(
        'product_id' => 49,
        'product_type' => Product::class,
        'selling_price' => 210000.0,
        'walk_in_rep_bonus' => $share = (($bonus = Arr::random([500, 1000])) * Arr::random([1, 0.3])),
        'online_rep_bonus' => $bonus - $share,
        'sales_channel_id' => 2,
        'online_rep_id' => random_int(2, 16),
        'sales_rep_id' => random_int(2, 10),
        'sales_rep_type' => SalesRep::class,
        'sale_confirmed_by' => NULL,
        'sale_confirmer_type' => NULL,
        'is_swap_transaction' => 0,
        'created_at' => '2020-02-03 00:00:00',
        'updated_at' => '2020-02-01 00:00:00',
        'deleted_at' => NULL,
      ),
      30 =>
      array(
        'product_id' => 1,
        'product_type' => Product::class,
        'selling_price' => 170000.0,
        'walk_in_rep_bonus' => $share = (($bonus = Arr::random([500, 1000])) * Arr::random([1, 0.3])),
        'online_rep_bonus' => $bonus - $share,
        'sales_channel_id' => 8,
        'online_rep_id' => random_int(2, 16),
        'sales_rep_id' => random_int(2, 10),
        'sales_rep_type' => SalesRep::class,
        'sale_confirmed_by' => NULL,
        'sale_confirmer_type' => NULL,
        'is_swap_transaction' => 0,
        'created_at' => '2020-01-29 00:00:00',
        'updated_at' => '2020-01-27 00:00:00',
        'deleted_at' => NULL,
      ),
      31 =>
      array(
        'product_id' => 41,
        'product_type' => Product::class,
        'selling_price' => 260000.0,
        'walk_in_rep_bonus' => $share = (($bonus = Arr::random([500, 1000])) * Arr::random([1, 0.3])),
        'online_rep_bonus' => $bonus - $share,
        'sales_channel_id' => 8,
        'online_rep_id' => random_int(2, 16),
        'sales_rep_id' => random_int(2, 10),
        'sales_rep_type' => SalesRep::class,
        'sale_confirmed_by' => NULL,
        'sale_confirmer_type' => NULL,
        'is_swap_transaction' => 0,
        'created_at' => '2020-01-25 00:00:00',
        'updated_at' => '2020-01-22 00:00:00',
        'deleted_at' => NULL,
      ),
      32 =>
      array(
        'product_id' => 8,
        'product_type' => Product::class,
        'selling_price' => 170000.0,
        'walk_in_rep_bonus' => $share = (($bonus = Arr::random([500, 1000])) * Arr::random([1, 0.3])),
        'online_rep_bonus' => $bonus - $share,
        'sales_channel_id' => 2,
        'online_rep_id' => random_int(2, 16),
        'sales_rep_id' => random_int(2, 10),
        'sales_rep_type' => SalesRep::class,
        'sale_confirmed_by' => NULL,
        'sale_confirmer_type' => NULL,
        'is_swap_transaction' => 0,
        'created_at' => '2020-01-20 00:00:00',
        'updated_at' => '2020-01-18 00:00:00',
        'deleted_at' => NULL,
      ),
      33 =>
      array(
        'product_id' => 12,
        'product_type' => Product::class,
        'selling_price' => 60000.0,
        'walk_in_rep_bonus' => $share = (($bonus = Arr::random([500, 1000])) * Arr::random([1, 0.3])),
        'online_rep_bonus' => $bonus - $share,
        'sales_channel_id' => 8,
        'online_rep_id' => random_int(2, 16),
        'sales_rep_id' => random_int(2, 10),
        'sales_rep_type' => SalesRep::class,
        'sale_confirmed_by' => NULL,
        'sale_confirmer_type' => NULL,
        'is_swap_transaction' => 0,
        'created_at' => '2020-01-15 00:00:00',
        'updated_at' => '2020-01-13 00:00:00',
        'deleted_at' => NULL,
      ),
      34 =>
      array(
        'product_id' => 33,
        'product_type' => Product::class,
        'selling_price' => 90000.0,
        'walk_in_rep_bonus' => $share = (($bonus = Arr::random([500, 1000])) * Arr::random([1, 0.3])),
        'online_rep_bonus' => $bonus - $share,
        'sales_channel_id' => 6,
        'online_rep_id' => random_int(2, 16),
        'sales_rep_id' => random_int(2, 10),
        'sales_rep_type' => SalesRep::class,
        'sale_confirmed_by' => NULL,
        'sale_confirmer_type' => NULL,
        'is_swap_transaction' => 0,
        'created_at' => '2020-01-11 00:00:00',
        'updated_at' => '2020-01-08 00:00:00',
        'deleted_at' => NULL,
      ),
      35 =>
      array(
        'product_id' => 40,
        'product_type' => Product::class,
        'selling_price' => 50000.0,
        'walk_in_rep_bonus' => $share = (($bonus = Arr::random([500, 1000])) * Arr::random([1, 0.3])),
        'online_rep_bonus' => $bonus - $share,
        'sales_channel_id' => 6,
        'online_rep_id' => random_int(2, 16),
        'sales_rep_id' => random_int(2, 10),
        'sales_rep_type' => SalesRep::class,
        'sale_confirmed_by' => NULL,
        'sale_confirmer_type' => NULL,
        'is_swap_transaction' => 0,
        'created_at' => '2020-01-06 00:00:00',
        'updated_at' => '2020-01-04 00:00:00',
        'deleted_at' => NULL,
      ),
      36 =>
      array(
        'product_id' => 34,
        'product_type' => Product::class,
        'selling_price' => 120000.0,
        'walk_in_rep_bonus' => $share = (($bonus = Arr::random([500, 1000])) * Arr::random([1, 0.3])),
        'online_rep_bonus' => $bonus - $share,
        'sales_channel_id' => 3,
        'online_rep_id' => random_int(2, 16),
        'sales_rep_id' => random_int(2, 10),
        'sales_rep_type' => SalesRep::class,
        'sale_confirmed_by' => NULL,
        'sale_confirmer_type' => NULL,
        'is_swap_transaction' => 0,
        'created_at' => '2020-01-01 00:00:00',
        'updated_at' => '2019-12-30 00:00:00',
        'deleted_at' => NULL,
      ),
      37 =>
      array(
        'product_id' => 27,
        'product_type' => Product::class,
        'selling_price' => 40000.0,
        'walk_in_rep_bonus' => $share = (($bonus = Arr::random([500, 1000])) * Arr::random([1, 0.3])),
        'online_rep_bonus' => $bonus - $share,
        'sales_channel_id' => 5,
        'online_rep_id' => random_int(2, 16),
        'sales_rep_id' => random_int(2, 10),
        'sales_rep_type' => SalesRep::class,
        'sale_confirmed_by' => NULL,
        'sale_confirmer_type' => NULL,
        'is_swap_transaction' => 0,
        'created_at' => '2019-12-28 00:00:00',
        'updated_at' => '2019-12-25 00:00:00',
        'deleted_at' => NULL,
      ),
    ));
  }
}
